apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  type: ClusterIP # not exposed to outside but internally it can be reached
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 80
