apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: bangarangler/kub-demo-tasks:latest
          env:
            - name: AUTH_ADDRESS
              # value: "10.109.136.79" # could do this or could use dynamic env var
              # this is being used in signup and dynamically in login
              value: "auth-service.default" # service name . name space
            - name: TASKS_FOLDER
              value: tasks
